### PR TITLE
shift ncbi urls from ftp to https protocol

### PR DESCRIPTION
**Pull request by wanjauk**
Using the  HTTPS protocol solves the error encountered on #27

### CODE REVIEW

**Comment by sherrillmix** [comment]
Thanks @wanjauk. I've been debating shifting from ftp to https but I didn't really have any evidence that moving to https is particularly better or would solve download issues. Do you have some evidence in that direction?

**Comment by wanjauk** [comment]
Hello @sherrillmix. I had the same issue as reported in #27 where a partial file was downloaded. I figured that it had to do with the ftp connection on my end so I tried using taxonomizr with https and it worked. I have tried to reproduce the error I got with ftp but it now works fine. So it may have been an issue with my ftp connection. Since I have not used/tested the https protocol with taxonomizr extensively, I have no evidence at the moment that using https would be better. I will keep you posted if anything comes up.

Here's my session info:
```> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] taxonomizr_0.8.1

loaded via a namespace (and not attached):
[1] compiler_4.0.2    data.table_1.14.0
```

**Comment by sherrillmix** [comment]
Thanks @wanjauk. Yeah that's exactly the same kind of experience I've been having. All these errors seem stochastic and/or very specific to a particular person's situation so it's been really hard to nail them down.

I guess I could add some sort of phone home to the package so I can log when it works or doesn't work and sessionInfo but that's starting to violate privacy more than I'd like if I was a user. More doably I should add a "try a few times before giving up and/or download manually" section to the README and help.

**Comment by wanjauk** [comment]
In the meantime, you can include some info about the issue on the  README and help page for the package. As time goes by, more details will come up that may shed light on the issue.

**Comment by sherrillmix** [comment]
Thanks again for the pull request! It's still not particularly clear to me which protocol is better so I added a `protocol` option to the functions so users can choose based on their preference (or things can be quickly updated if things change in the future). Notably both protocols allow resumption of interrupted downloads with the new [curl update](https://github.com/jeroen/curl/pull/285) (I had worried that would not be easily accessible with http).

**Pull request closed without merging**
